return {
  plugins = {
    "AstroNvim/astrocommunity",
    {
      "maxmx03/solarized.nvim",
      config = function() vim.o.background = "light" end,
    },
    {
      "navarasu/onedark.nvim",
    },
    { import = "astrocommunity.bars-and-lines.vim-illuminate" },
    { import = "astrocommunity.colorscheme.everforest" },
    { import = "astrocommunity.colorscheme.tokyonight-nvim" },
    { import = "astrocommunity.colorscheme.poimandres-nvim" },
    { import = "astrocommunity.colorscheme.onedarkpro-nvim" },
    { import = "astrocommunity.colorscheme.catppuccin" },
    { import = "astrocommunity.diagnostics.trouble-nvim" },
    { import = "astrocommunity.lsp.lsp-inlayhints-nvim" },
    { import = "astrocommunity.pack.bash" },
    { import = "astrocommunity.pack.go" },
    { import = "astrocommunity.pack.html-css" },
    { import = "astrocommunity.pack.json" },
    { import = "astrocommunity.pack.lua" },
    { import = "astrocommunity.pack.markdown" },
    { import = "astrocommunity.pack.proto" },
    { import = "astrocommunity.pack.python" },
    { import = "astrocommunity.pack.rust" },
    { import = "astrocommunity.pack.tailwindcss" },
    { import = "astrocommunity.pack.typescript" },
    { import = "astrocommunity.pack.vue" },
    -- { import = "astrocommunity.pack.dart" },
    { import = "astrocommunity.utility.noice-nvim" },
  },
  colorscheme = "catppuccin-macchiato",
}
